# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish fxhash-starter

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish --access public
        working-directory: "./peeler"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Publish to GHP
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        working-directory: "./peeler"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
